-- SQL para insertar modelos 8154, 3778, 9303  
  
INSERT INTO device_catalog (id, factory_model, model_name, usage_type, target_anatomy, stimulation_type, motor_logic, image_url, qr_code_url, supported_funcs, is_precise_new, broadcast_prefix) VALUES ('8154', 'GS001', 'Knight No. 3', 'Universal', 'Anal', 'Vibracion', 'Dual Channel', 'https://raw.githubusercontent.com/reneleyvaolace/velvetsynccatalog/main/documentacion/docs/img/VS_8154.jpg', 'https://raw.githubusercontent.com/reneleyvaolace/velvetsynccatalog/main/documentacion/docs/qr/QR_8154.png', 'classic,music,shake,intera,finger,video,game,explore', true, '77 62 4d 53 45') ON CONFLICT (id) DO UPDATE SET model_name = EXCLUDED.model_name;  
  
INSERT INTO device_catalog (id, factory_model, model_name, usage_type, target_anatomy, stimulation_type, motor_logic, image_url, qr_code_url, supported_funcs, is_precise_new, broadcast_prefix) VALUES ('3778', 'AAGS118', 'AAGS118', 'Universal', 'Universal', 'Vibracion', 'Single Channel', 'https://raw.githubusercontent.com/reneleyvaolace/velvetsynccatalog/main/documentacion/docs/img/VS_3778.jpg', 'https://raw.githubusercontent.com/reneleyvaolace/velvetsynccatalog/main/documentacion/docs/qr/QR_3778.png', 'classic,music,shake,intera,finger,video,game,explore', true, '77 62 4d 53 45') ON CONFLICT (id) DO UPDATE SET model_name = EXCLUDED.model_name;  
  
INSERT INTO device_catalog (id, factory_model, model_name, usage_type, target_anatomy, stimulation_type, motor_logic, image_url, qr_code_url, supported_funcs, is_precise_new, broadcast_prefix) VALUES ('9303', 'FJ001', 'FJ001', 'Universal', 'Universal', 'Vibracion', 'Single Channel', 'https://raw.githubusercontent.com/reneleyvaolace/velvetsynccatalog/main/documentacion/docs/img/VS_9303.jpg', 'https://raw.githubusercontent.com/reneleyvaolace/velvetsynccatalog/main/documentacion/docs/qr/QR_9303.png', 'classic,music,shake,intera,finger,video,game,explore', true, '77 62 4d 53 45') ON CONFLICT (id) DO UPDATE SET model_name = EXCLUDED.model_name;  
  
SELECT id, factory_model, model_name, usage_type, stimulation_type, motor_logic, is_precise_new FROM device_catalog WHERE id IN ('8154', '3778', '9303');  
