@echo off  
echo [Velvet Sync] Limpiando build corrupto...  
if exist build\windows\x64\flutter\ephemeral rmdir /s /q build\windows\x64\flutter\ephemeral  
echo [Velvet Sync] Obteniendo dependencias...  
call flutter pub get  
echo [Velvet Sync] Ejecutando app...  
call flutter run -d windows  
pause 
